#!/usr/bin/env python3
"""
generate_compose_generators.py - Splice the per-turbine generator services
into docker-compose.yml.

One container runs one turbine, so a nine-turbine fleet needs nine nearly
identical compose services. Writing them by hand invites the failure this
tool exists to prevent: a copy-pasted service that still carries the
previous turbine's TURBINE_ID or health port, which produces duplicate
data or a container that cannot bind its port -- both of which look like
a working stack until someone reads the data.

The generated block is delimited by BEGIN/END markers inside
docker-compose.yml so the rest of the file stays hand-maintained.

Regenerate after editing app/config/fleet.json:
    python app/tools/generate_compose_generators.py
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "app" / "src"))

from fleet import Turbine, load_fleet

COMPOSE_PATH = REPO_ROOT / "docker-compose.yml"
BEGIN_MARKER = "  # >>> BEGIN GENERATED TURBINE GENERATORS"
END_MARKER = "  # <<< END GENERATED TURBINE GENERATORS"

HEADER = """  # One container per turbine; only the ID and port env vars differ.
"""


def render_service(turbine: Turbine) -> str:
    return f"""  {turbine.service_name}:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: turbine-digitaltwin-app:latest
    container_name: turbine-{turbine.service_name}
    restart: unless-stopped
    command: ["python", "synthetic_producer.py"]
    depends_on:
      kafka:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - KAFKA_BOOTSTRAP_SERVERS_INTERNAL=kafka:29092
      - CUSTOMER_ID={turbine.customer_id}
      - SITE_ID={turbine.site_id}
      - TURBINE_ID={turbine.turbine_id}
      - LOG_DIR=/app/logs
      - HEALTH_CHECK_PORT={turbine.health_port}
    ports:
      - "{turbine.health_port}:{turbine.health_port}"
    volumes:
      - ./app/logs:/app/logs
      - ./app/config:/app/config:ro
    networks:
      - turbine-net
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:{turbine.health_port}/ready"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s
"""


def render_block() -> str:
    fleet = load_fleet()
    services = "\n".join(render_service(t) for t in fleet.turbines)
    return (
        f"{BEGIN_MARKER}\n"
        "  # Generated by app/tools/generate_compose_generators.py from\n"
        "  # app/config/fleet.json. Do not edit between these markers.\n"
        f"{HEADER}\n{services}{END_MARKER}\n"
    )


def splice(compose_text: str, block: str) -> str:
    begin = compose_text.find(BEGIN_MARKER)
    end = compose_text.find(END_MARKER)
    if begin == -1 or end == -1:
        raise SystemExit(
            f"markers not found in {COMPOSE_PATH}; add\n{BEGIN_MARKER}\n{END_MARKER}\n"
            "around the generator services first"
        )
    if end < begin:
        raise SystemExit("END marker precedes BEGIN marker in docker-compose.yml")
    return compose_text[:begin] + block + compose_text[end + len(END_MARKER) + 1 :]


def main() -> int:
    fleet = load_fleet()
    COMPOSE_PATH.write_text(splice(COMPOSE_PATH.read_text(), render_block()))
    print(f"Wrote {len(fleet.turbines)} generator services into {COMPOSE_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
