-- tenant-views.sql - GENERATED by app/tools/generate_postgres_init.py from app/config/fleet.json.
-- Do not edit by hand; regenerate instead.

-- ---- cross-customer admin role (Grafana org 1 dashboards) ------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'grafana_admin_reader') THEN
        CREATE ROLE grafana_admin_reader LOGIN;
    END IF;
END
$$;
ALTER ROLE grafana_admin_reader WITH PASSWORD :'grafana_password';
-- Read-only, everywhere, permanently: even a future GRANT on a new table
-- cannot make this role able to write.
ALTER ROLE grafana_admin_reader SET default_transaction_read_only = on;
GRANT CONNECT ON DATABASE :"db_name" TO grafana_admin_reader;
GRANT USAGE ON SCHEMA public TO grafana_admin_reader;
GRANT SELECT ON alerts, alert_breaches, turbine_states TO grafana_admin_reader;

-- Set default tenant_name if not provided via psql --set
\if :{?tenant_name}
\else
\set tenant_name 'zephyr-energy'
\endif

SELECT set_config('app.tenant_name', :'tenant_name', false);
SELECT set_config('app.grafana_password', :'grafana_password', false);
SELECT set_config('app.db_name', :'db_name', false);

-- ---- tenant role and isolated views ------------
DO $$
DECLARE
    v_tenant text := current_setting('app.tenant_name');
    v_role text := 'grafana_' || v_tenant;
    v_pw text := current_setting('app.grafana_password');
    v_db text := current_setting('app.db_name');
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = v_role) THEN
        EXECUTE format('CREATE ROLE %I LOGIN', v_role);
    END IF;
    EXECUTE format('ALTER ROLE %I WITH PASSWORD %L', v_role, v_pw);
    -- Read-only, everywhere, permanently: even a future GRANT on a new table
    -- cannot make this role able to write.
    EXECUTE format('ALTER ROLE %I SET default_transaction_read_only = on', v_role);
    EXECUTE format('GRANT CONNECT ON DATABASE %I TO %I', v_db, v_role);
    EXECUTE format('GRANT USAGE ON SCHEMA public TO %I', v_role);

    EXECUTE format('CREATE OR REPLACE VIEW %I AS SELECT * FROM alerts WHERE customer_id = %L', v_tenant || '_alerts', v_tenant);
    EXECUTE format('CREATE OR REPLACE VIEW %I AS SELECT * FROM alert_breaches WHERE customer_id = %L', v_tenant || '_alert_breaches', v_tenant);
    EXECUTE format('CREATE OR REPLACE VIEW %I AS SELECT * FROM turbine_states WHERE customer_id = %L', v_tenant || '_turbine_states', v_tenant);

    EXECUTE format('GRANT SELECT ON %I, %I, %I TO %I',
        v_tenant || '_alerts', v_tenant || '_alert_breaches', v_tenant || '_turbine_states', v_role);
    EXECUTE format('REVOKE ALL ON alerts, alert_breaches, turbine_states FROM %I', v_role);
END
$$;
